config/routes.rb
Green::Application.routes.draw do
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/auth/dropbox', :as => :dropbox_login
  devise_for :users do
    get '/users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session # :new_user_session
    delete '/users/logout' => 'devise/sessions#destroy', :as => :user_logout
  end

  resources :users, :only => [:show] do
    get :dropbox, :on => :member
    resources :tags
    resources :fotos do
      collection do
        put :collection, :action => 'update_collection'
        delete :collection, :action => 'destroy_collection'
      end
    end
  end
  

  
  root :to => 'green#show'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  include ActsAsEnabled
  mount_uploader :file, ImageUploader
  
  scope :be_queue, where(:fetch_state => nil)
  validates_uniqueness_of :token
  validates_presence_of :token
  validates_presence_of :url
  validates_presence_of :user_id
  serialize :data, Hash
  belongs_to :user
  has_many :taggings
  has_many :tags, :through => :taggings
  
  def has_thumb?
    url_thumb.present?
  end
  
  def data
    ActiveSupport::HashWithIndifferentAccess.new super
  end

  def filename_origin
    url.split("/").last
  end
  
  def fetch_async
    FotoWorker.perform_async(:fetch, id)
    update_column :fetch_state, :queuing
  end
  
  def fetch
    generate_thumb
    fetch_exif
    # fetch_origin_url
    update_column :fetch_state, (fetched? ? :finished : nil)
  end
  
  def next
    if !@next_foto
      ids = user.fotos.enabled.map(&:id)
      index = ids.index(id) || 0
      index = index - 1 if index > 0
      @next_foto = Foto.find(ids[index])
    end
    @next_foto
  end
  
  def prev
    if !@prev_foto
      ids = user.fotos.enabled.map(&:id).reverse
      index = ids.index(id) || 0
      index = index - 1 if index > 0
      @prev_foto = Foto.find(ids[index])
    end
    @prev_foto
  end
  
  private 
  
  def fetched?
    has_thumb? && datetime && width && height
  end

  def fetch_exif
    return unless file.file.path
    rmagick = Magick::Image.read(file.file.path).first
    datetime = rmagick.get_exif_by_entry('DateTimeOriginal').first.last
    update_attributes :width => rmagick.get_exif_by_entry('ExifImageWidth').first.last,
                      :height => rmagick.get_exif_by_entry('ExifImageLength').first.last,
                      :datetime => datetime.gsub(datetime[0..9], datetime[0..9].gsub(":", "-"))
  end
  
  def fetch_origin_url
    update_column :url, user.dropbox_client.media("/Camera Uploads/#{filename_origin.gsub("%20", " ")}")['url']
  end
  
  def generate_thumb
    return unless url.present?
    begin
      self.remote_file_url = url
      update_column(:url_thumb, file.thumb.url) if self.save
    rescue OpenURI::HTTPError
      self.disable
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def foto_file_path(foto)
    foto.has_thumb? ? foto.url_thumb : user_foto_path(foto.user, foto, :format => :jpg)
  end
  
  def foto_checked_number
    raw "<span id='foto_checked'>0</span>"
  end

  def body_classes(append_classes = nil)
    classes = [params[:controller].gsub("/","-"), params[:action]]
    if append_classes.is_a?(String)
      classes << append_classes 
    elsif append_classes.is_a?(Array)
      classes.concat(append_classes)
    end
    classes.join(" ")
  end
  
  def current_list_name
    if params[:tag_id] && @tag
      return @tag.name
    elsif params[:untagging]
      return untagging_fotos_name
    else
      return all_fotos_name
    end
  end
 
  def all_fotos_name
    "全部相片"
  end
  
  def untagging_fotos_name
    "尚未分類"
  end
  
end

app/views/application/_foot.html.haml
%span.links
  =link_to '關於 green foto',"#"
  |
  =link_to '聯絡我們',"#"
.clearfix
%span.copyright
  五樓專業團隊
.clearfix

app/views/application/_foto_cell.html.haml
.foto_cell
  .img{ :data => { :type => :foto } }
    %label{ :for => "foto_#{foto.id}" }
      = image_tag foto_file_path(foto), :class => :foto
    .checked
      %img{:src => asset_path('checked.png')}
  .icons
    = form.input_field :_id, :as => :boolean, :checked => false, :class => 'icon-ok-sign add foto_checked', :data => { :type => :fade, :to => ".foto_cell"}, :id => "foto_#{foto.id}"
    = link_to "#", :class => 'tagged' do
      %i.icon-bookmark
    = link_to user_foto_path(foto.user, foto) do
      .zoomin
        %i.icon-zoom-in

app/views/application/_foto_top.html.haml
.topbar.navbar.navbar-fixed-top
  .navbar-inner
    .pull-left
      = link_to "上一頁", user_fotos_path(current_user), :class => "btn-back"
    .pull-center
      - if @foto.datetime
        %span
          = "拍照時間:"
          = @foto.datetime
    .clearfix

app/views/application/_sub_bar.html.haml
.navbar.navbar-fixed-bottom
  .navbar-inner
    %button.remove.btn.btn-inverse{:type => :button, "data-toggle" => :modal, :href => "#removeModal"}
      ="移除"
    %button.add.btn.btn-inverse{:type => :button, "data-toggle" => :modal, :href => "#addModal"}
      ="加入"
    .pick
      已選取 3 張照片
    .clearfix
            
            
#removeModal.modal.hide
  .modal-header
    %button.close{"data-dismiss" => :modal, :type => :button} ×
  %h3.modal-body
    %p
      確定要從服務內移除
      %br
      已選取的 3 張照片嗎？
  .modal-footer
    %a.btn{"data-dismiss" => "modal", :href => "#"}
      取消
    %a.btn.btn-danger{:href => "#"}
      移除照片
#addModal.modal.hide
  .modal-header
    %button.close{"data-dismiss" => :modal, :type => :button} ×
    %h3
      加入分類
  .modal-body
    %p
      .tags
        - 10.times do |i|
          .tag
            .label
              美食
        .clearfix
      .input-append
        %input#appendedInputButton{:placeholder => "輸入新分類名稱",:size => "16", :type => "text"}
          %button.btn{:type => "button"} 新增
  .modal-footer
    %a.btn{"data-dismiss" => "modal", :href => "#"}
      取消
    %a.btn.btn-primary{:href => "#"}
      儲存

app/views/application/_subbar.html.haml
.navbar.navbar-fixed-bottom
  .navbar-inner
    .pull-left
      %button.btn-remove{:data => {:toggle => :modal}, :href => "#remove_modal"}
        ="移除"
    .pull-right
      %button.btn-add{:data => {:toggle => :modal}, :href => "#add_modal"}
        ="加入"
    .pull-center
      = raw "已選取 #{foto_checked_number} 張照片"
    .clearfix
            
- content_for :fotos_remove_modal do
  #remove_modal.modal.hide
    .modal-header
      %button.close{:data => {:dismiss => :modal} } ×
      .clearfix
    %h3.modal-body
      %p
        確定要從服務內移除
        %br
        = raw "已選取的 #{foto_checked_number} 張照片嗎？"
    .modal-footer
      = link_to "取消", "#", :class => :btn, :data => { :dismiss => :modal }
      = link_to "移除照片", "#", :class => 'btn btn-danger', :data => { :type => :form_request, :method => :delete }
      
- content_for :fotos_tagging_modal do
  #add_modal.modal.hide
    .modal-header
      %button.close{:data => {:dismiss => :modal} } ×
      %h3
        加入分類
    .modal-body
      %p
        .tags
          - current_user.tags.each do |tag|
            = render :partial => "tag", :object => tag, :locals => { :foto => @foto }
        .clearfix
        %form.form-inline.input-append
          %input#tag_add{ :placeholder => "輸入新分類名稱", :size => "16", :type => "text" }
            %input.btn{ :type => "button", :value => "新增", :data => { :type => :append_tag, :user_id => current_user.id, :from => "#tag_add", :to => ".modal-body .tags" } }
    .modal-footer
      = link_to "取消", "#", :class => :btn, :data => { :dismiss => :modal }
      = link_to "儲存", "#", :class => 'btn btn-primary', :data => { :type => :form_request, :method => :put }

app/views/application/_tag.html.haml
- tag_ids = local_assigns[:foto] ? foto.tag_ids : []
- checked = tag_ids.include?(tag.id)
.tag
  %button.btn.btn-inverse{:data => { :toggle => :button, :type => :tag_checkbox }, :onclick => "return false;", :class => (checked ? "active" : "") }
    = tag.name
  %input{ :type => :checkbox, :name => "foto[tag_ids][]", :value => tag.id, :checked => checked }

app/views/application/_topbar.html.haml
.topbar.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{ :data => { :target => ".nav-collapse", :toggle => :collapse } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Green Foto', root_path, :title => "green foto", :class => :brand
      .nav-collapse.collapse
        %ul.nav
          %li.active
            = link_to '首頁', '#', :title => "首頁"
          %li
            = link_to 'mypage', '#', :title => "mypage"
        %ul.pull-right
          - if user_signed_in?
            = link_to "Dropbox 同步", dropbox_user_path(current_user), :class => "btn btn-primary"
            = link_to "登出", user_logout_path, :method => :delete, :class => "btn btn-primary"
          - else
            = link_to "Dropbox 登入", dropbox_login_path, :class => "btn btn-primary"
          
          