config/routes.rb
Green::Application.routes.draw do
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
    
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/auth/dropbox', :as => :dropbox_login
  devise_for :users do
    get '/users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session # :new_user_session
    delete '/users/logout' => 'devise/sessions#destroy', :as => :user_logout
  end

  resources :users, :only => [:show] do
    get :dropbox, :on => :member
    resources :tags
    resources :fotos do
      collection do
        put :collection, :action => 'update_collection'
        delete :collection, :action => 'destroy_collection'
      end
    end
  end
  

  
  root :to => 'green#show'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  include ActsAsEnabled
  mount_uploader :file, ImageUploader
  
  scope :be_queue, where(:fetch_state => nil)
  validates_uniqueness_of :token
  validates_presence_of :token
  validates_presence_of :url
  validates_presence_of :user_id
  serialize :data, Hash
  belongs_to :user
  has_many :taggings
  has_many :tags, :through => :taggings
  
  def has_thumb?
    url_thumb.present?
  end
  
  def data
    ActiveSupport::HashWithIndifferentAccess.new super
  end

  def filename_origin
    url.split("/").last
  end
  
  def fetch_async
    FotoWorker.perform_async(:fetch, id)
    update_column :fetch_state, :queuing
  end
  
  def fetch
    generate_thumb
    fetch_exif
    # fetch_origin_url
    update_column :fetch_state, (fetched? ? :finished : nil)
  end
  
  def next
    if !@next_foto
      ids = user.fotos.enabled.map(&:id)
      index = ids.index(id) || 0
      index = index - 1 if index > 0
      @next_foto = Foto.find(ids[index])
    end
    @next_foto
  end
  
  def prev
    if !@prev_foto
      ids = user.fotos.enabled.map(&:id).reverse
      index = ids.index(id) || 0
      index = index - 1 if index > 0
      @prev_foto = Foto.find(ids[index])
    end
    @prev_foto
  end
  
  private 
  
  def fetched?
    has_thumb? && datetime && width && height
  end

  def fetch_exif
    return unless file.file.path
    rmagick = Magick::Image.read(file.file.path).first
    datetime = rmagick.get_exif_by_entry('DateTimeOriginal').first.last
    update_attributes :width => rmagick.get_exif_by_entry('ExifImageWidth').first.last,
                      :height => rmagick.get_exif_by_entry('ExifImageLength').first.last,
                      :datetime => datetime.gsub(datetime[0..9], datetime[0..9].gsub(":", "-"))
  end
  
  def fetch_origin_url
    update_column :url, user.dropbox_client.media("/Camera Uploads/#{filename_origin.gsub("%20", " ")}")['url']
  end
  
  def generate_thumb
    return unless url.present?
    begin
      self.remote_file_url = url
      update_column(:url_thumb, file.thumb.url) if self.save
    rescue OpenURI::HTTPError
      self.disable
    end
  end
  
end

app/controllers/foto_controller.rb
class FotoController < ApplicationController
  def index
    render :layout => "application"
  end
  def show
    render :layout => "application"
  end
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_foto_ids, :only => [ :destroy_collection, :update_collection ]
  
  def index
    @fotos = current_user.fotos.enabled.page(params[:page]).per(30)
    if params[:tag_id]
      @tag = Tag.find(params[:tag_id])
      @fotos = @fotos.where(:id => @tag.fotos.map(&:id)) 
    elsif params[:untagging]
      @fotos = @fotos.where(:taggings_count => 0) 
    end
  end
  
  def show
    @foto = current_user.fotos.find params[:id]
    if params[:format] == 'jpg'
      response.headers['Content-Type'] = 'image/jpeg'
      render :text => current_user.dropbox_client.thumbnail("Camera%20Uploads/#{@foto.filename_origin}", 'large')
    end
  end
  
  def update
    @foto = current_user.fotos.find params[:id]
    if @foto.update_attributes params[:foto]
      redirect_to request.env["HTTP_REFERER"] || user_fotos_path(current_user)
    end
  end
  
  def destroy_collection
    current_user.fotos.where(:id => @foto_ids).each do |foto|
      foto.disable
    end
    redirect_to user_fotos_path(current_user)
  end
  
  def update_collection
    append_tags(@foto_ids) if params[:foto] && (params[:foto][:tag_ids] || []).size > 0
    redirect_to user_fotos_path(current_user)
  end
  
  def destroy
    @foto = current_user.fotos.find params[:id]
    @foto.disable
    redirect_to(@foto.prev ? user_foto_path(current_user, @foto.prev) : user_fotos_path(current_user))
  end
  
  private 
  
  def append_tags(foto_ids)
    current_user.fotos.where(:id => @foto_ids).each do |foto|
      foto.update_attributes :tag_ids => (params[:foto][:tag_ids].map(&:to_i) + foto.tag_ids).uniq
    end
  end
  
  def load_foto_ids
    @foto_ids = params[:user][:fotos_attributes].values.select{ |tmp| tmp[:_id] == "1" }.map{ |tmp| tmp[:id] }
    @foto_ids << 0
  end
  
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_menu.html.haml
%ul.nav.nav-pills.nav-stacked
  %li.active
    = link_to current_list_name , "#", :data => { :type => :toggle, :to => "li.tags-tag" }
  - if current_list_name != all_fotos_name
    %li.tags-tag
      = link_to all_fotos_name, user_fotos_path(current_user)
  - if current_list_name != untagging_fotos_name
    %li.tags-tag
      = link_to untagging_fotos_name, user_fotos_path(current_user, :untagging => true)
  - current_user.tags.each do |tag|
    - next if tag.id.to_s == params[:tag_id]
    %li.tags-tag
      = link_to "#{tag.name} (#{tag.tagging_count})", user_fotos_path(current_user, :tag_id => tag.id)
  %li
    = simple_form_for Tag.new, :url => user_tags_path(current_user), :html => { :class => "form-inline input-append", :id => "fotos_form" }, :method => :post do |tag_form|
      = tag_form.input_field :name, :id => "appendedInputButton", :placeholder => "輸入新分類名稱", :size => 16
      = tag_form.submit " 新增", :class => :btn

app/views/fotos/index.html.haml
- content_for :topbar do
  = render :partial => "topbar"
- content_for :subbar do
  = render :partial => "subbar"

= render :partial => "menu"
  
.list
  = simple_form_for current_user, :url => collection_user_fotos_path(current_user) do |f|
    = f.simple_fields_for :fotos, @fotos do |foto_form|
      = render :partial => "foto_cell", :object => foto_form.object, :as => :foto, :locals => { :form => foto_form }
    .clearfix
    = yield :fotos_remove_modal
    = yield :fotos_tagging_modal

app/views/fotos/show.html.haml
- content_for :topbar do
  = render :partial => "foto_top"
- content_for :subbar do
  = render :partial => "subbar"

.pull-center{ :data => { :type => :mover, :show => ".buttons" } }
  %img{ :src => @foto.url, :width => "100%" }/
.buttons.next{ :data => { :type => :fixed, :right => 30, :top => :middle } }
  = link_to "NEXT", user_foto_path(current_user, @foto.next)
.buttons.prev{ :data => { :type => :fixed, :left => 30, :top => :middle } }
  = link_to "PREV", user_foto_path(current_user, @foto.prev)

= simple_form_for @foto, :url => user_foto_path(current_user, @foto), :html => { :force_submit => true } do |form|
  = yield :fotos_remove_modal
  = yield :fotos_tagging_modal